import { games, benefits, plans, launchEndsAt } from './data.js?v=18';

const gameGrid=document.querySelector('[data-game-grid]');const benefitList=document.querySelector('[data-benefit-list]');const planGrid=document.querySelector('[data-plan-grid]');const faqList=document.querySelector('[data-faq-list]');const toast=document.querySelector('[data-toast]');const year=document.querySelector('[data-year]');
const faqs=[{q:'O que é a NOT?',a:'A NOT é uma plataforma de acesso premium a jogos e experiências interativas, com planos para jogadores e uma área Creator para projetos personalizados.'},{q:'Como funciona o Conector NOT?',a:'O Conector NOT é a camada que integra recursos e interações compatíveis com a experiência da plataforma. Os recursos disponíveis dependem do plano contratado.'},{q:'Preciso instalar alguma coisa?',a:'O acesso principal é feito pela web. Quando algum jogo ou recurso exigir uma etapa adicional, a NOT informa isso de forma clara antes do uso.'},{q:'Funciona no celular e no PC?',a:'Sim. A interface foi estruturada para funcionar em dispositivos móveis e computadores, com testes automatizados em Safari, Chrome e Android.'},{q:'Qual a diferença entre Normal, Plus e Premium?',a:'O Normal é a porta de entrada, o Plus amplia catálogo e benefícios, e o Premium libera a experiência mais completa, incluindo acesso antecipado e prioridade em novidades.'},{q:'Como funciona o NOT Creator?',a:'Você apresenta a ideia do jogo ou experiência para sua live, a equipe NOT define o escopo e entrega um projeto web personalizado, com integração e testes conforme o orçamento.'},{q:'Posso cancelar minha assinatura?',a:'Sim. As regras de cancelamento, renovação e cobrança serão exibidas de forma objetiva no checkout e na área da conta antes da contratação.'},{q:'O que acontece quando acabar o preço de lançamento?',a:'A condição promocional termina em 01/11/2026. Depois dessa data, passam a valer os preços regulares exibidos nos planos.'}];
if(year)year.textContent=new Date().getFullYear();
let lastTouchEnd=0;document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});document.addEventListener('gestureend',e=>e.preventDefault(),{passive:false});document.addEventListener('touchmove',e=>{if(e.touches.length>1)e.preventDefault()},{passive:false});document.addEventListener('touchend',e=>{const n=Date.now();if(n-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=n},{passive:false});document.addEventListener('dblclick',e=>e.preventDefault());
const launchDeadline=new Date(launchEndsAt).getTime();const isLaunchActive=()=>Date.now()<launchDeadline;let offerRevealed=false;

const catalogGames=[
 {name:'Caos Live',meta:'Sobrevivência · Mundo aberto',status:'Disponível',available:true,accent:'#b8ff3d'},
 {name:'Merge Live',meta:'Combine · Evolua · Interaja',status:'Disponível',available:true,accent:'#74f2ce'},
 {name:'WAR',meta:'Combate',status:'Em desenvolvimento',available:false,accent:'#8290ff'},
 {name:'Slot 04',meta:'Nova experiência',status:'Manutenção',available:false,accent:'#657080'},
 {name:'Slot 05',meta:'Nova experiência',status:'Manutenção',available:false,accent:'#657080'}
];
function demoMarkup(game,index){return `<div class="catalog-demo" data-demo="${index}" style="--game-accent:${game.accent}"><div class="demo-top"><span><i></i> DEMONSTRAÇÃO · ${game.name.toUpperCase()}</span><small>prévia interativa</small></div><div class="demo-stage"><div class="demo-grid"></div><div class="demo-orb orb-a"></div><div class="demo-orb orb-b"></div><div class="demo-player"><span>NOT</span></div><div class="demo-target target-a"></div><div class="demo-target target-b"></div><div class="demo-event">Pronto para interagir</div></div><div class="demo-controls"><button type="button" data-demo-action="0">INTERAÇÃO</button><button type="button" data-demo-action="1">PRESENTE</button><button type="button" data-demo-action="2">EVENTO</button></div></div>`}
function renderGames(){if(!gameGrid)return;gameGrid.classList.add('catalog-selector');gameGrid.innerHTML=`<div class="catalog-list">${catalogGames.map((g,i)=>`<button class="catalog-row ${g.available?'available':'disabled'} ${i===0?'selected':''}" type="button" ${g.available?`data-select-game="${i}"`:''} style="--game-accent:${g.accent}"><span class="catalog-index">${String(i+1).padStart(2,'0')}</span><span class="catalog-name"><strong>${g.name}</strong><small>${g.meta}</small></span><span class="catalog-status"><i></i>${g.status}</span><b class="catalog-arrow">${g.available?'↗':'—'}</b></button>`).join('')}</div><div class="catalog-preview">${demoMarkup(catalogGames[0],0)}</div>`}
function selectGame(index){const g=catalogGames[index];if(!g?.available)return;document.querySelectorAll('.catalog-row').forEach((r,i)=>r.classList.toggle('selected',i===index));const preview=gameGrid.querySelector('.catalog-preview');preview.innerHTML=demoMarkup(g,index);preview.classList.remove('preview-in');void preview.offsetWidth;preview.classList.add('preview-in')}

function renderBenefits(){if(!benefitList)return;benefitList.innerHTML=benefits.map(i=>`<article class="benefit-item"><span class="benefit-number">${i.number}</span><div><h3>${i.title}</h3><p>${i.description}</p></div></article>`).join('')}
function renderFaqs(){if(!faqList)return;faqList.innerHTML=faqs.map((i,x)=>`<article class="faq-item"><button class="faq-question" type="button" aria-expanded="false" aria-controls="faq-answer-${x}"><span>${i.q}</span><span class="faq-icon" aria-hidden="true"></span></button><div class="faq-answer" id="faq-answer-${x}"><div><p>${i.a}</p></div></div></article>`).join('')}
function discountPercent(r,l){return Math.round((1-Number(l.replace(',','.'))/Number(r.replace(',','.')))*100)}
function countdownMarkup(){const r=Math.max(0,launchDeadline-Date.now()),t=Math.floor(r/1000),d=Math.floor(t/86400),h=Math.floor(t%86400/3600),m=Math.floor(t%3600/60),s=t%60;return `<div class="card-offer-timer"><span class="timer-label"><i></i> oferta por tempo limitado</span><div class="timer-values"><b>${d}</b><small>dias</small><b>${h}</b><small>h</small><b>${m}</b><small>min</small><b>${s}</b><small>seg</small></div></div>`}
function renderPlanFeatures(p){if(p.commercial)return p.features.map(f=>`<span class="feature-item included">${f}</span>`).join('');return p.features.map(f=>`<span class="feature-item ${f.included?'included':'unavailable'}">${f.label}</span>`).join('')}
function renderPlans(){if(!planGrid)return;const active=isLaunchActive();planGrid.innerHTML=plans.map(p=>{let price='';if(p.commercial)price=`<div class="creator-symbol" aria-hidden="true">&lt;/&gt;</div><h3 class="creator-headline">${p.headline}</h3><div class="commercial-price">${p.priceLabel}</div>`;else if(active&&offerRevealed){const d=discountPercent(p.regularPrice,p.launchPrice);price=`<div class="offer-activated"><i></i> OFERTA ATIVADA</div><div class="price-offer-row"><span class="regular-price">R$ ${p.regularPrice}</span><span class="discount-pill">-${d}%</span></div><div class="launch-price-row price-reveal"><span class="currency">R$</span><strong>${p.launchPrice}</strong><small>${p.suffix}</small></div>${countdownMarkup()}`}else price=`<div class="regular-entry-price"><span class="currency">R$</span><strong>${p.regularPrice}</strong><small>${p.suffix}</small></div><span class="regular-entry-caption">valor regular</span>`;return `<article class="plan-card ${p.featured?'featured':''} ${p.commercial?'commercial':''} ${offerRevealed&&active&&!p.commercial?'offer-active':''}"><div class="plan-label">${p.name}${p.badge?`<span>${p.badge}</span>`:''}</div>${price}<p class="plan-description">${p.description}</p><div class="plan-features">${renderPlanFeatures(p)}</div><button class="primary-button" type="button" data-action="${p.commercial?'creator':'subscribe'}" data-plan="${p.name}">${p.commercial?'Solicitar projeto':`Escolher ${p.name}`} <span>↗</span></button></article>`}).join('')}
function revealOfferInCards(){if(!isLaunchActive())return;setTimeout(()=>{offerRevealed=true;renderPlans()},1450)}function updateCardCountdowns(){if(!offerRevealed||!isLaunchActive())return;document.querySelectorAll('.card-offer-timer').forEach(timer=>{const r=Math.max(0,launchDeadline-Date.now()),t=Math.floor(r/1000),d=Math.floor(t/86400),h=Math.floor(t%86400/3600),m=Math.floor(t%3600/60),s=t%60;timer.querySelector('.timer-values').innerHTML=`<b>${d}</b><small>dias</small><b>${h}</b><small>h</small><b>${m}</b><small>min</small><b>${s}</b><small>seg</small>`})}function showToast(m){if(!toast)return;toast.textContent=m;toast.classList.add('visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('visible'),2600)}
const demoMessages=[['AUDIÊNCIA ENTROU','NOVO PARTICIPANTE'],['PRESENTE RECEBIDO','COMBINAÇÃO EVOLUIU'],['EVENTO ATIVADO','MODO ESPECIAL']];function triggerDemo(btn){const demo=btn.closest('.catalog-demo');if(!demo)return;const a=Number(btn.dataset.demoAction||0),i=Number(demo.dataset.demo||0),stage=demo.querySelector('.demo-stage'),ev=demo.querySelector('.demo-event');ev.textContent=demoMessages[a]?.[i]||demoMessages[a]?.[0]||'INTERAÇÃO ATIVADA';stage.classList.remove('pulse-0','pulse-1','pulse-2');void stage.offsetWidth;stage.classList.add(`pulse-${a}`)}
document.addEventListener('click',e=>{const select=e.target.closest('[data-select-game]');if(select){selectGame(Number(select.dataset.selectGame));return}const da=e.target.closest('[data-demo-action]');if(da){triggerDemo(da);return}const fq=e.target.closest('.faq-question');if(fq){const item=fq.closest('.faq-item'),open=!item.classList.contains('open');document.querySelectorAll('.faq-item.open').forEach(o=>{o.classList.remove('open');o.querySelector('.faq-question')?.setAttribute('aria-expanded','false')});if(open){item.classList.add('open');fq.setAttribute('aria-expanded','true')}return}const ft=e.target.closest('.footer-toggle');if(ft){ft.closest('.footer-group')?.classList.toggle('open');return}const target=e.target.closest('[data-action]');if(!target)return;if(target.dataset.action==='login')showToast('Login Firebase será conectado na próxima etapa.');if(target.dataset.action==='subscribe')showToast(`Plano ${target.dataset.plan} selecionado. Checkout entra na próxima etapa.`);if(target.dataset.action==='creator')showToast('Conte sua ideia para a NOT. O formulário de orçamento entra na próxima etapa.')});
renderGames();renderBenefits();renderPlans();renderFaqs();revealOfferInCards();setInterval(updateCardCountdowns,1000);